on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Hello world action step
      id: hello
      uses: ../actions/test_bot/
      with:
        who-to-great: 'Mona the Octocat'
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
