on:
  pull_request:
    types: [opened, synchronize]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Python deps
      run: |
        python -m pip install --upgrade black flake8 flake8-json
    - name: Hello world action step
      id: hello
      uses: ./.github/actions/test_bot
      with:
        who-to-greet: 'Mona the Octocat'
        token: '${{ secrets.GITHUB_TOKEN }}'
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
